config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    if @task.save
    redirect_to task_path(@task.id), notice: "タスクを作成しました!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    
    @task = Task.find(params[:id])
    if @task.update(task_params)
    redirect_to tasks_path, notice: "タスクを編集しました！"
  else
    render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "タスクを削除しました"
  end

  private

  def task_params
    params.require(:task).permit(:title, :content)
  end

  def set_task
  @task = Task.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyoh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="task_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="button">
  <%= form.submit %>
  </div>
  <%= link_to "タスク一覧画面にもどる", tasks_path %>
<% end %>

app/views/tasks/edit.html.erb
　<h2>タスクを編集する</h2>

  <%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    
    <td><%= link_to '詳細を確認する', task_path(task.id) %></td>
    <td><%= link_to "タスクを編集する", edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' } %><td>
    <td><%= link_to 'タスクを削除する', task_path(task.id), method: :delete , data: { confirm: '本当に削除していいですか？' }%><td>

  </tr>
<% end %>

</table>
<%= link_to '新しくタスクを作成する', new_task_path %>

app/views/tasks/new.html.erb
  <h2>タスクを作成する</h2>

  <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タイトル: <%= @task.title %></p>
<p>内容: <%= @task.content %></p>

  <%= link_to "タスク一覧画面にもどる", tasks_path %>